#**Welocme to Numpy Library**

In [1]:
import numpy as np

myarr = np.array([[3,4,56,7]])
myarr[0,1]


4

In [2]:
myarr.shape

(1, 4)

In [3]:
myarr.dtype

dtype('int32')

In [4]:
myarr[0,0]= 6
myarr

array([[ 6,  4, 56,  7]])

In [5]:
myarr

array([[ 6,  4, 56,  7]])

In [6]:
myarr.size

4

In [7]:
zeros=np.zeros((2,5))

In [8]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
zeros.dtype

dtype('float64')

In [10]:
zeros.size

10

In [11]:
zeros[1,2]=2

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0.]])

In [13]:
zeros.shape

(2, 5)

In [14]:
rng=np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace=np.linspace(1,5,12)

In [17]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
lspace=np.linspace(1,5,4)

In [19]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [20]:
empt=np.empty((2,3))

In [21]:
empt

array([[3.19929910e-308, 3.47906303e-308, 2.21717754e-301],
       [3.34291778e-287, 1.45422304e-296, 1.64324269e-287]])

In [22]:
empt[0,2]=4444

In [23]:
empt

array([[3.19929910e-308, 3.47906303e-308, 4.44400000e+003],
       [3.34291778e-287, 1.45422304e-296, 1.64324269e-287]])

In [24]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
ide=np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
ide.shape

(10, 10)

In [28]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [29]:
arr.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [30]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr=arr.reshape(9,1)
arr

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [33]:
arr.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr=arr.ravel()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [40]:
ar.max(axis=0)

array([7, 5, 6])

In [41]:
ar.max(axis=1)

array([3, 6, 7])

In [42]:
ar.min(axis=0)

array([1, 1, 0])

In [43]:
ar.min(axis=1)

array([1, 4, 0])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar
    



array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
reverse=np.flipud(ar)
reverse

array([[7, 1, 0],
       [4, 5, 6],
       [1, 2, 3]])

In [49]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim

2

In [52]:
y=np.zeros([2,1,3])
y

array([[[0., 0., 0.]],

       [[0., 0., 0.]]])

In [53]:
y.shape

(2, 1, 3)

In [54]:
y.size

6

In [55]:
y.ndim

3

In [56]:
y.nbytes

48

In [57]:
one=np.array([1,3,2,4,8,7,6])
one.argmax()

4

In [58]:
one.argmin()

0

In [59]:
one.argsort()

array([0, 2, 1, 3, 6, 5, 4], dtype=int32)

In [60]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.argmax()

6

In [62]:
ar.argmin()

8

In [63]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [64]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [65]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [66]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int32)

In [67]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [69]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [70]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [71]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [72]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])
ar2=np.array([[1,2,1],[4,6,5],[7,9,8]])
ar+ar2

array([[ 2,  4,  4],
       [ 8, 11, 11],
       [14, 10,  8]])

In [73]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])
ar2=np.array([[1,2,1],[4,6,5],[7,9,8]])
ar2-ar

array([[ 0,  0, -2],
       [ 0,  1, -1],
       [ 0,  8,  8]])

In [74]:
ar*ar2

array([[ 1,  4,  3],
       [16, 30, 30],
       [49,  9,  0]])

In [75]:
ar/ar2

array([[1.        , 1.        , 3.        ],
       [1.        , 0.83333333, 1.2       ],
       [1.        , 0.11111111, 0.        ]])

In [76]:
ar2//ar

C:\Users\NABAKU~1\AppData\Local\Temp/ipykernel_7384/2259292195.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  ar2//ar


array([[1, 1, 0],
       [1, 1, 0],
       [1, 9, 0]], dtype=int32)

In [79]:
np.sqrt(ar)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [80]:
ar.sum()

29

In [81]:
ar2.sum()

43

In [83]:
ar.max()

7

In [84]:
ar.min()

0

In [85]:
np.where(ar>2)

(array([0, 1, 1, 1, 2], dtype=int32), array([2, 0, 1, 2, 0], dtype=int32))

In [86]:
np.count_nonzero(ar)

8

In [88]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [89]:
ar[1,1]=0

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int32))

In [91]:
np.ar_tolist()

AttributeError: module 'numpy' has no attribute 'ar_tolist'

In [92]:
np_ar.tolist()

NameError: name 'np_ar' is not defined

In [94]:
np.tolist(ar)

AttributeError: module 'numpy' has no attribute 'tolist'